agent:
  name: OpenAIAgent
  args:
    api_key: sk-iKDxVf6Uap69SsSUBbC642C48f8e44Ce861f2941CcE278Ab
    api_base: "https://one-api.glm.ai/v1"
    model_name: "gpt-4o-2024-05-13"
    max_new_tokens: 512

task:
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 25
    request_interval: 3
    mode: "in_app"

eval:
  avd_base: /Users/xuyifan/.android/avd
  avd_name: Pixel_7_Pro_API_33_v2
  avd_log_dir: ./logs/evaluation
  android_sdk_path: /Users/xuyifan/Library/Android/sdk
