agent:
  name: OpenAIAgent
  args:
    api_key: sk-iKDxVf6Uap69SsSUBbC642C48f8e44Ce861f2941CcE278Ab
    api_base: "https://one-api.glm.ai/v1"
    model_name: "gpt-4o-2024-05-13"
    max_new_tokens: 512

task:
  class: ScreenshotMobileTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 15
    request_interval: 5
    mode: "in_app"

eval:
  avd_name: test_Android
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:aitw
    port: 6060
    local_port: 6700
  version: "v2"

