agent:
  name: GLMModelAgent_0801
  args:
    api_base: "http://172.18.195.227:8080"
    temperature: 0.9


task:
  class: TextOnlyMobileTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 25
    request_interval: 8
    mode: "in_app"

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:v3
    port: 6060
    local_port: 6500
  version: "v2"

