agent:
  name: GLM4Agent
  args:
    model_key: a9e4c4bc2c3c8f5b026ec10488b7b485.SZHOUgvPfCEKbztk
    model_name: "glm-4-0520"
    temperature: 0.0
    max_new_tokens: 512

task:
  class: TextOnlyMobileTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 15
    request_interval: 3
    mode: "in_app"

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:v2
    port: 6060
  version: "v2"