agent:
  name: CogagentAgent_09
  relative_bbox: "True"
  args:
    url: "http://172.18.192.100:24020/v1/general"

task:
  class: CogAgentTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 25
    request_interval: 3
    mode: "in_app"

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:v2
    port: 6060
    local_port: 6000
  version: "v2"
