agent:
  name: LLaMAModelAgent_0801
  args:
    api_base: "http://172.18.192.104:10010/v1/chat/completions"
    temperature: 1.0


task:
  class: TextOnlyMobileTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 25
    request_interval: 20
    mode: "in_app"

eval:
  avd_name: test_Android
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:aitw
    port: 6060
    local_port: 6700
  version: "v2"

