agent:
  name: Swift_agent
  relative_bbox: "True"
  args:
    model_name: "glm4v-9b-chat"
    url: "http://172.18.192.104:10011/v1/chat/completions"


task:
  class: QwenVLAgentTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 25
    request_interval: 5
    mode: "in_app"

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:v2
    port: 6060
    local_port: 6600
  version: "v2"
