agent:
  name: Qwen2VLAgent
  relative_bbox: "True"
  args:
    url: "http://172.18.192.104:10012/v1/chat/completions"
    model_name: Qwen2-VL-2B-Instruct


task:
  class: QwenVLAgentTask_AutoTest
  args:
    save_dir: "./logs/evaluation"
    max_rounds: 25
    request_interval: 5
    mode: "in_app"

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:v2
    port: 6060
    local_port: 6000
  version: "v2"
